FROM python:3.9-slim

WORKDIR /usr/src/app
COPY . .

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0

CMD ["celery", "-A", "application.celery_app", "worker", "--loglevel=info"]
