services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 -k gevent app:application --workers=3
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A app:celery_app worker --loglevel=info --concurrency=8
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A app:celery_app beat --loglevel=info --schedule=/usr/src/app/tmp/celerybeat-schedule
    volumes:
      - .:/usr/src/app
      - celerybeat-schedule:/usr/src/app/tmp
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
  celerybeat-schedule: