version: '3.8'

services:
  web:
    build: .
    command: uwsgi --http :8000 --gevent 1000 --http-websockets --master --wsgi-file application.py --callable application
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
