version: '3.8'

services:
  web:
    build: .
    command: uwsgi --http 0.0.0.0:8000 --module app:application --master --processes 3 --threads 2
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
