version: '3.8'

services:
  web:
    build: .
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 0.0.0.0:8000 application:application
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
