tech_skills = [
    'Python', 'JavaScript', 'Java', 'HTML', 'CSS', 'SQL', 'PL/SQL', 'Data Analysis', 'Machine Learning',
    'React', 'Angular', 'Vue.js', 'Node.js', 'Django', 'Flask', 'Ruby', 'Ruby on Rails',
    'C#', '.NET', 'ASP.NET', 'ASP.NET Core', 'PHP', 'Laravel', 'Symfony', 'WordPress',
    'Swift', 'iOS', 'Objective-C', 'Android', 'Kotlin', 'Flutter', 'React Native', 'Ionic',
    'TensorFlow', 'PyTorch', 'Keras', 'Scikit-learn', 'Natural Language Processing', 'Computer Vision',
    'Big Data', 'Hadoop', 'Spark', 'MongoDB', 'MySQL', 'PostgreSQL', 'Oracle', 'Firebase',
    'Git', 'GitHub', 'Bitbucket', 'Jenkins', 'Travis CI', 'Docker', 'Kubernetes', 'AWS',
    'Azure', 'Google Cloud Platform', 'RESTful APIs', 'GraphQL', 'OAuth', 'JSON', 'XML',
    'Microservices', 'Test-Driven Development', 'Selenium', 'JUnit', 'Pytest', 'Cypress', 'Jest',
    'Agile Methodology', 'Scrum', 'DevOps', 'Continuous Integration', 'Continuous Deployment',
    'Blockchain', 'Smart Contracts', 'Solidity', 'Ethereum', 'Web Development', 'Mobile Development', 'Data Science',
    'Artificial Intelligence', 'Virtual Reality', 'Augmented Reality', 'Cybersecurity', 'Penetration Testing', 'Network Administration',
    'UI/UX Design', 'Responsive Web Design', 'Accessibility', 'Progressive Web Apps', 'Serverless Architecture', 'NoSQL',
    'GraphQL', 'TypeScript', 'Spring Boot', 'ASP.NET MVC', 'Vue.js', 'Nuxt.js', 'Gatsby', 'Express.js',
    'Redux', 'MobX', 'GraphQL', 'RESTful APIs', 'WebSocket', 'Jest', 'Enzyme', 'Cypress', 'JUnit',
    'Postman', 'Swagger', 'Jira', 'Confluence', 'Trello', 'Slack', 'Kibana', 'Grafana', 'ELK Stack',
    'Splunk', 'New Relic', 'Bugzilla', 'Load Testing', 'Performance Testing', 'Security Testing', 'Code Review',
    'Static Analysis', 'Code Quality', 'Linting', 'Unit Testing', 'Integration Testing', 'System Testing', 'Acceptance Testing',
    'R', 'Scala', 'Go', 'C', 'C++', 'Perl', 'Shell Scripting', 'Data Engineering', 'Data Warehousing',
    'Tableau', 'Power BI', 'Data Visualization', 'ETL', 'Apache Kafka', 'Apache Spark', 'AWS Glue',
    'Natural Language Processing', 'Computer Vision', 'Reinforcement Learning', 'Deep Learning', 'Neural Networks',
    'Cloud Computing', 'Serverless Architecture', 'Microservices', 'Kubernetes', 'Terraform', 'Ansible', 'Puppet',
    'Blockchain Development', 'Smart Contracts', 'Cryptocurrency', 'Solidity', 'Ethereum', 'Web Development',
    'Front-End Development', 'Back-End Development', 'Full-Stack Development', 'Responsive Web Design', 'UI/UX Design',
    'Progressive Web Apps', 'Mobile App Development', 'iOS Development', 'Android Development', 'Cross-Platform Development',
    'AR/VR Development', 'Game Development', 'Cybersecurity', 'Ethical Hacking', 'Penetration Testing', 'Network Security',
    'Information Security', 'Security Operations', 'Cloud Security', 'DevOps', 'Infrastructure as Code', 'CI/CD',
    'Monitoring and Alerting', 'Containerization', 'Microservices Architecture', 'Serverless Computing', 'NoSQL Databases',
    'Data Analysis', 'Business Intelligence', 'Statistical Analysis', 'Data Mining', 'Machine Learning',
    'Big Data Technologies', 'Cloud Computing', 'Data Governance', 'Data Engineering', 'Data Pipelines',
    'ETL Processes', 'Data Modeling', 'Business Analytics', 'Predictive Analytics', 'IoT', 'Firmware Development',
    'Embedded Systems', 'Robotics', 'Natural Language Processing', 'Speech Recognition', 'Virtual Assistants',
    'Geospatial Analysis', 'Geographic Information Systems (GIS)', 'Quantum Computing', 'Bioinformatics',
    'Genomics', 'Healthcare Informatics', 'Fintech', 'Payment Gateways', 'E-commerce', 'ERP Systems',
    'CRM Systems', 'Supply Chain Management', 'Agile Methodology', 'Scrum', 'Lean Software Development',
    'Design Thinking', 'UX Research', 'Mobile UX Design', 'Accessibility', 'Usability Testing',
    'Digital Marketing', 'SEO', 'Social Media Marketing', 'Content Management Systems', 'WordPress Development',
    'Artificial Intelligence', 'Robotics Process Automation (RPA)', 'Robotic Process Automation (RPA)', 'Cloud-Native Development',
    'Serverless Computing', 'Internet of Things (IoT)', 'Edge Computing', 'Natural Language Generation (NLG)', 'Quantum Computing',
    'Smart Contracts', 'Decentralized Finance (DeFi)', 'Cybersecurity', 'Ethical Hacking', 'Threat Intelligence',
    'Cloud Security', 'Identity and Access Management (IAM)', 'SecDevOps', 'Containerization', 'Microservices Architecture',
    'Event-Driven Architecture (EDA)', 'Data Engineering', 'Data Governance', 'Data Privacy', 'Data Visualization',
    'Machine Learning Operations (MLOps)', 'Big Data Analytics', 'Streaming Data Processing', 'Graph Databases',
    'Geospatial Analysis', 'Computer Vision', 'Augmented Reality (AR)', 'Virtual Reality (VR)', 'Extended Reality (XR)',
    'Internet of Medical Things (IoMT)', 'Healthcare Informatics', 'Precision Medicine', 'Bioinformatics', 'Fintech',
    'RegTech', 'Insurtech', 'Payment Gateways', 'Cryptocurrencies', 'E-commerce Platforms', 'Agile Project Management',
    'Scrum', 'Kanban', 'Lean Methodology', 'User-Centered Design (UCD)', 'Human-Computer Interaction (HCI)',
    'UI/UX Prototyping', 'Voice User Interface (VUI) Design', 'User Research', 'Social Media Marketing', 'Content Strategy',
    'Search Engine Optimization (SEO)', 'Data-Driven Marketing', 'Marketing Analytics', 'Conversion Rate Optimization (CRO)',
    'Salesforce CRM', 'Customer Relationship Management (CRM)', 'Supply Chain Management', 'Business Process Automation',
    'ERP Systems', 'ERP Implementation', 'Business Intelligence (BI)', 'Data Warehousing', 'Data Integration',
    'Data Collection', 'Predictive Models', 'Data Mining', 'Data Visualization', 'Data Storytelling', 
    'Data Governance', 'Data Privacy', 'Data Security', 'Data Quality', 'Data Catalog', 'Data Pipelines',
    'Data Ops', 'ML Ops', 'Rust'
]

tech_jobs = [
    "Software Developer",
    "Web Developer",
    "Mobile Developer",
    "Software Engineer",
    "Python Developer",
    "Java Developer",
    "Data Scientist",
    "Data Analyst",
    "Systems Analyst",
    "Network Engineer",
    "Database Administrator",
    "DevOps Engineer",
    "Cloud Architect",
    "Cybersecurity Analyst",
    "IT Project Manager",
    "Mobile App Developer",
    "UI/UX Designer",
    "Product Manager",
    "Artificial Intelligence (AI) Engineer",
    "Machine Learning Engineer",
    "IT Support Specialist",
    "IT Consultant",
    "Systems Administrator",
    "Network Administrator",
    "Quality Assurance (QA) Tester",
    "Business Analyst",
    "IT Manager",
    "Full Stack Developer",
    "Front End Developer",
    "Back End Developer",
    "Game Designer",
    "Blockchain Developer",
    "Game Developer",
    "Network Security Engineer",
    "Cloud Engineer",
    "Business Intelligence (BI) Analyst",
    "Computer Programmer",
    "IT Trainer",
    "IT Auditor",
    "Robotics Engineer",
    "Virtual Reality (VR) Developer",
    "Augmented Reality (AR) Developer",
    "Wireless Network Engineer",
    "Embedded Systems Developer",
    "IT Sales Professional",
    "Mobile Application Tester",
    "Network Architect",
    "IT Compliance Analyst",
    "Data Engineer",
    "IT Recruiter",
    "Hardware Engineer"
]
